### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by Spartan03168** [CADWRDeltaModeling/pydsm#36]
* pydsm version:
* Not sure
* Python version:
* 3.10.6
* Operating System:
* windows 11

### Description
I am failing to install it no matter what I do.
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I tries the traditional method of using pip install in the terminal. That failed.
I tried to install it using a tarball. I was expecting it to work. Failure.
I was using pycharm and tried to intall by hovering over the module name. Failure. 

### What I Did
Output 1
(venv) PS C:\Users\Tomy\PycharmProjects\Experiment - 7> pip install pydsm
Collecting pydsm
  Using cached pydsm-0.14.0.0.zip (552 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Tomy\AppData\Local\Temp\pip-install-33wcelaz\pydsm_85d060a8141c42bb8945c0de9e6188dd\setup.py", line 28, in <module>
          from Cython.Distutils import build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by kjnam** [comment]
@Spartan03168 It looks like you are trying to install this: https://github.com/sergiocallegari/PyDSM, not the package from this repository.
